name: Build, Push, and Deploy Docker Image

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build Docker Image
        run: docker build -t safump/foodu-backend:latest .
        
      - name: Publish Image to Docker Hub
        run: docker push safump/foodu-backend:latest 

  deploy:
    needs: build
    runs-on: ubuntu-latest  # Or use a self-hosted runner if deploying on a different server
    steps:
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Pull Image from Docker Hub
        run: docker pull safump/foodu-backend:latest 
        
      - name: Stop and Remove Old Container
        run: |
          docker stop foodu-backend-container || true
          docker rm foodu-backend-container || true

      - name: Run Docker Container
        run: |
          docker run -d -p 3028:3028 --name foodu-backend-container \
            -e DB_URL="${{ secrets.DB_URL }}" \
            safump/foodu-backend:latest
